name: Pytest  flake8 control Push
on: push

env:
  DAY_OF_WEEK: Lundi ## Variable d'env pour l'ensemble du flux de travail

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    env:
      Greeting: Salut ## Vaiable d'env pour la tache
    steps:
      - name: "Dites Salut Monalisa nous sommes Lundi"
        run: echo "$Greeting $First_Name. Nous sommes $DAY_OF_WEEK!"
        env:
          First_Name: MonaLisa ## Variable d'env uniquement pour l'étape

      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest


